// Generated by gencpp from file gpar_lidar/CommandResponse.msg
// DO NOT EDIT!


#ifndef GPAR_LIDAR_MESSAGE_COMMANDRESPONSE_H
#define GPAR_LIDAR_MESSAGE_COMMANDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gpar_lidar
{
template <class ContainerAllocator>
struct CommandResponse_
{
  typedef CommandResponse_<ContainerAllocator> Type;

  CommandResponse_()
    : command_res(0)  {
    }
  CommandResponse_(const ContainerAllocator& _alloc)
    : command_res(0)  {
  (void)_alloc;
    }



   typedef int8_t _command_res_type;
  _command_res_type command_res;





  typedef boost::shared_ptr< ::gpar_lidar::CommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gpar_lidar::CommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CommandResponse_

typedef ::gpar_lidar::CommandResponse_<std::allocator<void> > CommandResponse;

typedef boost::shared_ptr< ::gpar_lidar::CommandResponse > CommandResponsePtr;
typedef boost::shared_ptr< ::gpar_lidar::CommandResponse const> CommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gpar_lidar::CommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gpar_lidar::CommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gpar_lidar::CommandResponse_<ContainerAllocator1> & lhs, const ::gpar_lidar::CommandResponse_<ContainerAllocator2> & rhs)
{
  return lhs.command_res == rhs.command_res;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gpar_lidar::CommandResponse_<ContainerAllocator1> & lhs, const ::gpar_lidar::CommandResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gpar_lidar

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gpar_lidar::CommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gpar_lidar::CommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gpar_lidar::CommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gpar_lidar::CommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gpar_lidar::CommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gpar_lidar::CommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gpar_lidar::CommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9511c56212cea577d97085195522f876";
  }

  static const char* value(const ::gpar_lidar::CommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9511c56212cea577ULL;
  static const uint64_t static_value2 = 0xd97085195522f876ULL;
};

template<class ContainerAllocator>
struct DataType< ::gpar_lidar::CommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gpar_lidar/CommandResponse";
  }

  static const char* value(const ::gpar_lidar::CommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gpar_lidar::CommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 command_res\n"
"\n"
;
  }

  static const char* value(const ::gpar_lidar::CommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gpar_lidar::CommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command_res);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gpar_lidar::CommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gpar_lidar::CommandResponse_<ContainerAllocator>& v)
  {
    s << indent << "command_res: ";
    Printer<int8_t>::stream(s, indent + "  ", v.command_res);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GPAR_LIDAR_MESSAGE_COMMANDRESPONSE_H
